# Generated by Django 4.0.6 on 2022-07-21 14:27

import Ecommerce_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecommerce_Product_Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Name')),
                ('link', models.URLField(verbose_name='Link')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Ecommerce_products.models.upload_image_path, verbose_name='Slider-Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.CharField(max_length=1500)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(null=True)),
                ('picture', models.ImageField(blank=True, upload_to=Ecommerce_products.models.upload_image_path, verbose_name='Picture')),
                ('pic1', models.ImageField(blank=True, default='products/pic-225x155.png', upload_to=Ecommerce_products.models.upload_image_path, verbose_name='First picture for detail page')),
                ('pic2', models.ImageField(blank=True, default='products/pic-225x155.png', upload_to=Ecommerce_products.models.upload_image_path, verbose_name='Second picture for detail page')),
                ('pic3', models.ImageField(blank=True, default='products/pic-225x155.png', upload_to=Ecommerce_products.models.upload_image_path, verbose_name='Third picture for detail page')),
                ('active', models.BooleanField(default=True, verbose_name='Availability')),
                ('hotitem', models.BooleanField(default=True, verbose_name='Hot-items')),
                ('category', models.ManyToManyField(to='Ecommerce_Product_Category.productscategory')),
            ],
        ),
    ]
