# Generated by Django 4.0.6 on 2022-07-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic3',
        ),
    ]
