# Generated by Django 4.0.6 on 2022-07-22 07:59

import Ecommerce_products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_products', '0002_remove_product_pic1_remove_product_pic2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Ecommerce_products.models.upload_Gallery_image_path, verbose_name='Slider-Picture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_products.product')),
            ],
        ),
    ]
