# Generated by Django 4.0.6 on 2022-07-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_products', '0003_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=True, verbose_name='Show in recommendation products'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_products.product', verbose_name='Product'),
        ),
    ]
