# Generated by Django 4.0.6 on 2022-07-22 14:13

import Ecommerce_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_products', '0004_product_recommend_alter_productgallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to=Ecommerce_products.models.upload_image_path, verbose_name='Picture'),
        ),
    ]
