# Generated by Django 4.1 on 2022-08-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_products', '0014_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='is free?'),
        ),
        migrations.AddField(
            model_name='product',
            name='zip_file',
            field=models.FileField(default='', upload_to='', verbose_name='Upload Product'),
        ),
    ]
