# Generated by Django 4.1 on 2022-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_products', '0016_alter_product_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='zip_file',
            field=models.FileField(default='', upload_to='products_file', verbose_name='Upload Product(Zip File)'),
        ),
    ]
