# Generated by Django 4.1 on 2022-08-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_User_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='publish_date',
            new_name='date',
        ),
    ]
