# Generated by Django 4.1 on 2022-08-12 11:56

import Ecommerce_User_Dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce_User_Dashboard', '0003_alter_newsmodel_options_alter_newsmodel_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='First Name', max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='Last Name', max_length=150, null=True, verbose_name='Last Name')),
                ('mobile', models.CharField(blank=True, default='Mobile Number', max_length=150, null=True, verbose_name='Mobile')),
                ('talk', models.TextField(blank=True, default='Talk about yourself in one line', max_length=500, null=True, verbose_name='Talk')),
                ('country', models.CharField(blank=True, default='YourCountry', max_length=150, null=True, verbose_name='country')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_picture', models.ImageField(default='/media_root/profile/70*70.png', upload_to=Ecommerce_User_Dashboard.models.upload_image_path, verbose_name='Picture')),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
