# Generated by Django 4.1 on 2022-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_User_Dashboard', '0005_userprofile_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateTimeField(default='27/04/1987'),
        ),
    ]
