# Generated by Django 4.1 on 2022-08-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_User_Dashboard', '0007_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='(999) 999-9999', max_length=150, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='programmer',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='talk',
            field=models.TextField(blank=True, default='Talk about yourself in one line.', max_length=500, null=True, verbose_name='Talk'),
        ),
    ]
