# Generated by Django 4.1 on 2022-08-12 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_User_Dashboard', '0009_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=150, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
