# Generated by Django 4.1 on 2022-08-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_User_Dashboard', '0010_alter_userprofile_birth_day_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
