# Generated by Django 4.1 on 2022-08-12 15:09

import Ecommerce_User_Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_User_Dashboard', '0012_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/media_root/profile/70*70.png', null=True, upload_to=Ecommerce_User_Dashboard.models.upload_image_path, verbose_name='Picture'),
        ),
    ]
