# Generated by Django 4.1 on 2022-08-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_User_Dashboard', '0013_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='email'),
        ),
    ]
