# Generated by Django 4.0.6 on 2022-08-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_post_options_rename_create_post_create_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='publish',
        ),
    ]
