# Generated by Django 4.0.6 on 2022-08-04 11:32

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_post_options_rename_publish_post_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to=Blog.models.upload_image_path, verbose_name='Picture'),
        ),
    ]
