# Generated by Django 4.0.6 on 2022-08-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_body',
            field=models.CharField(default='', max_length=300, verbose_name='Short Body'),
        ),
    ]
