# Generated by Django 4.0.6 on 2022-08-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_post_short_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_body',
            field=models.TextField(default='', max_length=300, verbose_name='Short Body'),
        ),
    ]
