# Generated by Django 4.0.6 on 2022-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_post_short_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_body',
        ),
        migrations.AddField(
            model_name='post',
            name='post_explanation',
            field=models.TextField(default='', max_length=300, verbose_name='Explain about post with 300 character'),
        ),
    ]
