# Generated by Django 4.1 on 2022-08-07 11:05

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Blog', '0016_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='Visiting Number'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='post Tags'),
        ),
    ]
