# Generated by Django 4.1 on 2022-08-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_postscategory_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postscategory',
            name='name',
        ),
    ]
