# Generated by Django 4.0.6 on 2022-07-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecommerce_products', '0004_product_recommend_alter_productgallery_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Set Time')),
                ('active', models.BooleanField(default=True, verbose_name='Active/ Reactive')),
                ('products', models.ManyToManyField(blank=True, to='Ecommerce_products.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
