# Generated by Django 4.0.6 on 2022-07-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_read', models.BooleanField(verbose_name='Read / Unread')),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'User Contacts',
            },
        ),
    ]
