# Generated by Django 4.0.6 on 2022-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.TextField(default='', verbose_name='Phone'),
        ),
    ]
