# Generated by Django 4.0.6 on 2022-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Contact', '0002_contactus_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.TextField(default='', null=True, verbose_name='Phone'),
        ),
    ]
