# Generated by Django 4.0.6 on 2022-07-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_Contact', '0005_alter_contactus_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact us', 'verbose_name_plural': 'Users Contacts'},
        ),
    ]
