# Generated by Django 4.0.6 on 2022-07-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_about_us', '0003_alter_teammembers_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammembers',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'User Contacts'},
        ),
        migrations.RenameField(
            model_name='teammembers',
            old_name='name',
            new_name='title',
        ),
    ]
