# Generated by Django 4.0.6 on 2022-07-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_about_us', '0004_alter_teammembers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammembers',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
