# Generated by Django 4.0.6 on 2022-07-26 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecommerce_products', '0011_product_visit_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_session_id', models.CharField(blank=True, max_length=400)),
                ('get_paid', models.BooleanField(default=False, verbose_name=' Get Paid')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Paid')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Product Price')),
                ('count', models.IntegerField(blank=True, verbose_name='Count')),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_order.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce_products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'verbose_name_plural': 'Products Detail information',
            },
        ),
    ]
