# Generated by Django 4.0.6 on 2022-07-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='owner_session_id',
            new_name='owner_session',
        ),
    ]
