# Generated by Django 4.0.6 on 2022-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_order', '0003_alter_cart_owner_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='owner_session',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
