# Generated by Django 4.1 on 2022-08-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_order', '0006_orderitem_buy_date_orderitem_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='get_paid',
        ),
    ]
