# Generated by Django 4.0.6 on 2022-07-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Site Title')),
                ('address', models.CharField(max_length=400, null=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=50, null=True, verbose_name='Mobile')),
                ('fax', models.CharField(max_length=50, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Email')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='About us')),
                ('copy_right', models.CharField(blank=True, max_length=200, null=True, verbose_name='Copyright')),
            ],
        ),
    ]
