# Generated by Django 4.0.6 on 2022-07-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='first_email',
            field=models.EmailField(max_length=50, null=True, verbose_name='First Email Address'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='first_mobile',
            field=models.CharField(max_length=50, null=True, verbose_name='First Mobile Number'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='first_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='First Phone Number'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='second_email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Second Email Address'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='second_mobile',
            field=models.CharField(max_length=50, null=True, verbose_name='Second Mobile Number'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='second_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Second Phone Number'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='third_email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Third Email Address'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='third_mobile',
            field=models.CharField(max_length=50, null=True, verbose_name='Third Mobile Number'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='third_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Third Phone Number'),
        ),
    ]
