# Generated by Django 4.0.6 on 2022-07-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0002_remove_sitesetting_email_remove_sitesetting_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site setting', 'verbose_name_plural': 'Site Management'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='First Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Second Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Third Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Phone Number'),
        ),
    ]
