# Generated by Django 4.0.6 on 2022-07-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0004_alter_sitesetting_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='First Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Second Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Second Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Second Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Third Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Third Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Third Phone Number'),
        ),
    ]
