# Generated by Django 4.0.6 on 2022-07-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0005_alter_sitesetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='FaceBook Link'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter Link'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='about_us',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='About us'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copy_right',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fax'),
        ),
    ]
