# Generated by Django 4.0.6 on 2022-07-22 21:42

import Ecommerce_setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0006_sitesetting_facebook_sitesetting_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to=Ecommerce_setting.models.upload_logo_image_path, verbose_name='Logo in footer'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to=Ecommerce_setting.models.upload_logo_image_path, verbose_name='Logo in header'),
        ),
    ]
