# Generated by Django 4.0.6 on 2022-07-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0008_alter_sitesetting_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='about_us',
            new_name='Introduce',
        ),
    ]
