# Generated by Django 4.0.6 on 2022-07-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0009_rename_about_us_sitesetting_introduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='Introduce',
            new_name='introduce',
        ),
    ]
