# Generated by Django 4.0.6 on 2022-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0011_sitesetting_description_alter_sitesetting_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, default='Your Address in Site Management', max_length=400, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copy_right',
            field=models.CharField(blank=True, default='write your Copyright in site management', max_length=150, null=True, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook',
            field=models.URLField(blank=True, default='FaceBook address', verbose_name='FaceBook Link'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='fax',
            field=models.CharField(blank=True, default='Fax number Number', max_length=50, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_email',
            field=models.EmailField(blank=True, default='esf.shiran@gmail.com', max_length=50, verbose_name='First Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_mobile',
            field=models.CharField(blank=True, default='09366449561', max_length=50, verbose_name='First Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='first_phone',
            field=models.CharField(blank=True, default='09366449567', max_length=50, verbose_name='First Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, default='Instagram address', verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='introduce',
            field=models.TextField(blank=True, default='write in Site Management who you are', max_length=400, null=True, verbose_name='Who you are ?'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_email',
            field=models.EmailField(blank=True, default='Second email address', max_length=50, verbose_name='Second Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_mobile',
            field=models.CharField(blank=True, default='Second Mobile Number', max_length=50, verbose_name='Second Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_phone',
            field=models.CharField(blank=True, default='second phone number', max_length=50, verbose_name='Second Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_email',
            field=models.EmailField(blank=True, default='Third email address', max_length=50, verbose_name='Third Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_mobile',
            field=models.CharField(blank=True, default='Third Mobile Number', max_length=50, verbose_name='Third Mobile Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_phone',
            field=models.CharField(blank=True, default='Third Phone Number', max_length=50, verbose_name='Third Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(default='Your Title in Site Management', max_length=150, verbose_name='Site Title'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='twitter',
            field=models.URLField(blank=True, default='Twitter address', verbose_name='Twitter Link'),
        ),
    ]
