# Generated by Django 4.0.6 on 2022-07-27 21:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0013_alter_sitesetting_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='description',
            field=ckeditor.fields.RichTextField(default=' ', max_length=30000, verbose_name='Full descriptions'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='second_email',
            field=models.EmailField(blank=True, default='SecondEmail@email.com', max_length=50, verbose_name='Second Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='third_email',
            field=models.EmailField(blank=True, default='ThirsEmail@email.com', max_length=50, verbose_name='Third Email Address'),
        ),
    ]
