# Generated by Django 4.0.6 on 2022-07-27 21:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0014_alter_sitesetting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='description',
            field=ckeditor.fields.RichTextField(default='Write Full Description in SiteManegmante', max_length=30000, verbose_name='Full descriptions'),
        ),
    ]
