# Generated by Django 4.0.6 on 2022-07-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0016_sitesetting_team_of_service_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='team_of_service_rules',
            new_name='terms_of_service',
        ),
    ]
