# Generated by Django 4.1 on 2022-08-06 15:50

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Ecommerce_setting', '0017_rename_team_of_service_rules_sitesetting_terms_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
