# Generated by Django 4.1 on 2022-08-06 16:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Ecommerce_setting', '0018_sitesetting_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Blog Tags'),
        ),
    ]
