# Generated by Django 4.1 on 2022-08-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0019_alter_sitesetting_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Your Bank Account', max_length=150, verbose_name='Title ')),
                ('data_key', models.CharField(default='pk_test_TYooMQauvdEDq54NiTphI7jx', max_length=1000, verbose_name='PUBLIC KEY')),
                ('stripe_api_key', models.CharField(default='sk_test_4eC39HqLyjWDarjtT1zdp7dc', max_length=1000, verbose_name='SECRET KEY')),
                ('description', models.CharField(default='E-Commerce', max_length=1000, verbose_name='Description')),
                ('currency', models.CharField(default='usd', max_length=1000, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Account',
            },
        ),
    ]
