# Generated by Django 4.1 on 2022-08-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0020_bankaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='data_key',
            new_name='public_key',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='stripe_api_key',
            new_name='secret_key',
        ),
    ]
