# Generated by Django 4.1 on 2022-08-15 09:02

import Ecommerce_setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_setting', '0021_rename_data_key_bankaccount_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_logo',
            field=models.ImageField(blank=True, default='/media_root/logo/white_logo.png', null=True, upload_to=Ecommerce_setting.models.upload_logo_image_path, verbose_name='Logo in footer'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='header_logo',
            field=models.ImageField(blank=True, default='/media_root/logo/black_logo.png', null=True, upload_to=Ecommerce_setting.models.upload_logo_image_path, verbose_name='Logo in header'),
        ),
    ]
